[package]
name = "ew"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = { version = "4.5.1", features = [ "openssl" ] }
rusqlite = { version = "0.30.0", features = ["bundled"] }
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "4.4.6", features = ["derive"]}
base64 = "0.21.5"
json = "0.12.4"
rand = "0.8.5"
lazy_static = "1.4.0"
chrono = "0.4.31"
hex = "0.4.3"
hmac = "0.12.1"
md5 = "0.7.0"
urlencoding = "2.1.3"
sha1 = "0.10.6"
substring = "1.4.5"
uuid = { version = "1.8.0", features = ["v7"] }
rsa = "0.9.6"
mime = "0.3.17"
sha2 = "0.10.8"
include-flate-codegen = "0.3.0"
libflate = "2.1.0"
